-- Ticket: 1
-- Description: create_core_table
-- Schema: inventories
-- Type: structure
-- Date: ~0,4-~4,2-~6,2
-- Author: nppna

-- =============================================================================
-- MIGRATION: create_core_table
-- =============================================================================
-- Purpose: [Detailed explanation of why this change is needed]
--
-- Impact:
--   - Tables affected: inventories.[table_name]
--   - Estimated execution time: [X seconds]
--   - Backward compatible: [Yes/No]
--   - Requires data migration: [Yes/No]
--
-- Testing:
--   - [ ] Tested on local database
--   - [ ] Verified with existing data
--   - [ ] Application tested
--
-- Rollback:
--   - Method: Create new migration to undo
-- =============================================================================

-- =============================================================================
-- STRUCTURE MIGRATION - Schema Changes
-- =============================================================================

-- Example: Create Table
-- CREATE TABLE IF NOT EXISTS inventories.table_name (
--     "Id" BIGSERIAL PRIMARY KEY,
--     "Name" VARCHAR(255) NOT NULL,
--     "Status" VARCHAR(5) DEFAULT 'ACT',
--     "CreatedOn" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     "CreatedBy" VARCHAR(100),
--     "ModifiedOn" TIMESTAMP,
--     "ModifiedBy" VARCHAR(100)
-- );

-- Example: Add Column
-- ALTER TABLE inventories.table_name
-- ADD COLUMN IF NOT EXISTS "ColumnName" VARCHAR(255);

-- Example: Create Index
-- CREATE INDEX IF NOT EXISTS idx_table_column
-- ON inventories.table_name("ColumnName");

-- Add your migration SQL here:


-- =============================================================================
-- POST-MIGRATION VALIDATION
-- =============================================================================

-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1 FROM information_schema.columns
--         WHERE table_schema = 'inventories'
--         AND table_name = 'table_name'
--         AND column_name = 'ColumnName'
--     ) THEN
--         RAISE EXCEPTION 'Migration failed: Column not created';
--     END IF;
--
--     RAISE NOTICE 'Migration completed successfully';
-- END $$;

--CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS inventories;

-- PRODUCT
CREATE TABLE inventories.products (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryId" BIGINT,
    "ColorId" BIGINT,
    "SizeId" BIGINT,
    "Price" DECIMAL,
    "Name" VARCHAR(200),
    "Description" TEXT,
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- PRODUCT_IMAGE
CREATE TABLE inventories.product_images (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "productId" BIGINT,
    "url" VARCHAR(255),
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- COLORS
CREATE TABLE inventories.colors (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200),
    "ColorCode" VARCHAR(200),
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- SIZES    
CREATE TABLE inventories.sizes (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200),
    "Description" TEXT,
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- CATEGORIES
CREATE TABLE inventories.categories (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200),
    "Description" TEXT,
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- STOCKS
CREATE TABLE inventories.stocks (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" BIGINT,
    "Quantity" INT,
    "Status" VARCHAR(5),
    "CreatedOn" TIMESTAMP,
    "CreatedBy" VARCHAR(100),
    "ModifiedOn" TIMESTAMP,
    "ModifiedBy" VARCHAR(100)
);

-- =============================================================================
-- FOREIGN KEYS
-- =============================================================================
ALTER TABLE inventories.products
    ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("CategoryId") REFERENCES inventories.categories("Id"),
    ADD CONSTRAINT "fk_product_color" FOREIGN KEY ("ColorId") REFERENCES inventories.colors("Id"),
    ADD CONSTRAINT "fk_product_size" FOREIGN KEY ("SizeId") REFERENCES inventories.sizes("Id");

ALTER TABLE inventories.product_images
    ADD CONSTRAINT "fk_product_image_product" FOREIGN KEY ("productId") REFERENCES inventories.products("Id");

ALTER TABLE inventories.stocks
    ADD CONSTRAINT "fk_stock_product" FOREIGN KEY ("ProductId") REFERENCES inventories.products("Id");